export const OPEN_MODAL_INGREDIENT = 'OPEN_MODAL_INGREDIENT'
export const OPEN_MODAL_ORDER = 'OPEN_MODAL_ORDER'
export const CLOUSE_MODAL_INGREDIENT = 'CLOUSE_MODAL_INGREDIENT'
export const CLOUSE_MODAL_ORDER = 'CLOUSE_MODAL_ORDER'



